# Generated by Django 4.2.4 on 2023-08-17 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('location_field', models.CharField(help_text='Enter your location', max_length=50)),
            ],
            options={
                'ordering': ['-location_field'],
            },
        ),
    ]
