# Generated by Django 4.2.4 on 2023-08-17 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('precip_prob_field', models.CharField(max_length=10)),
                ('wind_speed_field', models.CharField(max_length=10)),
                ('wind_dir_field', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.location')),
            ],
        ),
    ]
