# Generated by Django 4.2.4 on 2023-08-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat_field',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='location',
            name='long_field',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
