# Generated by Django 4.2.4 on 2023-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_location_lat_field_location_long_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_field',
            field=models.CharField(help_text='Enter your location', max_length=300),
        ),
    ]
