# Generated by Django 4.2.4 on 2023-08-21 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_location_location_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='location',
        ),
        migrations.AddField(
            model_name='weather',
            name='location_id',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.location'),
        ),
    ]
