# Generated by Django 4.2.4 on 2023-08-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_weather_id_remove_weather_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='location_id',
            new_name='location',
        ),
    ]
