# Generated by Django 4.2.4 on 2023-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_location_id_weather_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='weather_condition_field',
            field=models.CharField(default='No condition', max_length=100),
        ),
    ]
